"""add role_assignment employee_id index

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-22 10:05:49.247555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_role_assignment_employee_id', 'role_assignment', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_role_assignment_employee_id', table_name='role_assignment')
    # ### end Alembic commands ###
