"""ticket fk indexes

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-22 23:11:53.903735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ticket_assignee_id', 'ticket', ['assignee_id'], unique=False)
    op.create_index('ix_ticket_queue_id', 'ticket', ['queue_id'], unique=False)
    op.create_index('ix_ticket_requester_id', 'ticket', ['requester_id'], unique=False)
    op.create_index('ix_ticket_message_ticket_id', 'ticket_message', ['ticket_id'], unique=False)
    op.create_index('ix_ticket_state_transition_ticket_id', 'ticket_state_transition', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticket_state_transition_ticket_id', table_name='ticket_state_transition')
    op.drop_index('ix_ticket_message_ticket_id', table_name='ticket_message')
    op.drop_index('ix_ticket_requester_id', table_name='ticket')
    op.drop_index('ix_ticket_queue_id', table_name='ticket')
    op.drop_index('ix_ticket_assignee_id', table_name='ticket')
    # ### end Alembic commands ###
