"""model call and pricing version

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-24 06:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0006'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('input_cost_per_1k_tokens_usd', sa.Float(), nullable=False),
    sa.Column('output_cost_per_1k_tokens_usd', sa.Float(), nullable=False),
    sa.Column('effective_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('pricing_version_id', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pricing_version_id'], ['pricing_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_call_purpose', 'model_call', ['purpose'], unique=False)
    # ### end Alembic commands ###

    # Seed a $0.00 PricingVersion row for the local self-hosted Ollama model
    # (infra Task 1: `ollama/qwen3:14b` via the LiteLLM proxy). Ollama calls
    # have zero marginal cost, but ModelCall rows still need a real
    # PricingVersion row to reference via the FK above -- this avoids
    # special-casing "no pricing row means free" in application code.
    pricing_version = sa.table(
        'pricing_version',
        sa.column('provider', sa.String()),
        sa.column('model', sa.String()),
        sa.column('input_cost_per_1k_tokens_usd', sa.Float()),
        sa.column('output_cost_per_1k_tokens_usd', sa.Float()),
    )
    op.bulk_insert(
        pricing_version,
        [
            {
                'provider': 'ollama',
                'model': 'qwen3:14b',
                'input_cost_per_1k_tokens_usd': 0.0,
                'output_cost_per_1k_tokens_usd': 0.0,
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_model_call_purpose', table_name='model_call')
    op.drop_table('model_call')
    op.drop_table('pricing_version')
    # ### end Alembic commands ###
